# Generated by Django 5.2.1 on 2025-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_remove_user_name_bassindata_bassin_id_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bassindata',
            name='bassin_id',
            field=models.CharField(default='BASSIN_DEFAULT', max_length=100),
        ),
    ]
